<a href="https://colab.research.google.com/github/balalahippo/helloworld/blob/numpy/nromalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
array1 = np.random.randint(0,11,(5,5))
array1

array([[ 9,  2,  5,  6,  5],
       [10,  1,  8,  4,  5],
       [ 2,  1,  7,  8,  1],
       [ 3,  3, 10,  7,  4],
       [ 6,  5,  4,  0,  6]])

三种归一化方法 ：1 绝对值归一化

In [8]:
array1_min = array1.min()
array1_max = array1.max()
array1_normal_way1 = ( array1 - array1_min )/(array1_max - array1_min)
array1_normal_way1

array([[0.9, 0.2, 0.5, 0.6, 0.5],
       [1. , 0.1, 0.8, 0.4, 0.5],
       [0.2, 0.1, 0.7, 0.8, 0.1],
       [0.3, 0.3, 1. , 0.7, 0.4],
       [0.6, 0.5, 0.4, 0. , 0.6]])

          2 方差归一化

In [9]:
array1 = np.array(array1,dtype='float32')
array1

array([[ 9.,  2.,  5.,  6.,  5.],
       [10.,  1.,  8.,  4.,  5.],
       [ 2.,  1.,  7.,  8.,  1.],
       [ 3.,  3., 10.,  7.,  4.],
       [ 6.,  5.,  4.,  0.,  6.]], dtype=float32)

In [10]:
array1_normal_way2 = (array1 - array1.mean())/(array1.std())
array1_normal_way2

array([[ 1.4690322 , -1.0268964 ,  0.0427873 ,  0.3993485 ,  0.0427873 ],
       [ 1.8255934 , -1.3834575 ,  1.112471  , -0.3137739 ,  0.0427873 ],
       [-1.0268964 , -1.3834575 ,  0.75590974,  1.112471  , -1.3834575 ],
       [-0.6703351 , -0.6703351 ,  1.8255934 ,  0.75590974, -0.3137739 ],
       [ 0.3993485 ,  0.0427873 , -0.3137739 , -1.7400187 ,  0.3993485 ]],
      dtype=float32)